AllCops:
  Exclude:
    - telegram-bot-kabushiki.gemspec
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Lint/RescueException:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/UnneededInterpolation:
  Exclude:
    - 'src/format_helper.rb'
Style/TrivialAccessors:
  Exclude:
    - 'src/parser/watch_parser.rb'

Metrics/LineLength:
  Max: 120
