en:
  emoji:
  instruction: |
    i fetch finance data from yahoo \n

    /list - gives stocks available in this bot
    /stat - (expert mode) provides details about the stock counter /stat GOOG
  welcome_reply: "hi, %{name} %{emoji}"
  negative_reply: "sorry %{name}, i cant find [%{param}] in /%{cmd}"
  exception_log: "killed by %{name} %{id} %{msg} %{e}\n"
  invalid_command_reply: "%{emoji} %{msg} not found"
  invalid_param_reply: "%{emoji} %{msg} not valid. type only alphabet, number and ."
  watch_reply: "you are watching %{param}"
  watch_nothing_reply: "you are not watching any stock"

