en:
  emoji:
  instruction: |
    i fetch finance data from yahoo \n

    /list - gives stocks available in this bot
    /rate - get currency rate and chart using 3-digit currency code /rate usdeur
    /stock - states the last traded price of *one* stock counter /stock Z78.SI
    /charts - (expert mode) depicts the graphical %change of some of the matching SG stocks and STI /charts bank
    /stat - (expert mode) provides details about the stock counter /stat GOOG
  welcome: "hi, %{name} %{emoji}"
  negative: "sorry %{name}, i cant find [%{param}] in /%{cmd}"
  exception: "killed by %{name} %{id} %{msg} %{e}\n"
  invalid_command: "%{emoji} %{msg} not found"
  invalid_param: "%{emoji} %{msg} not valid. type only alphabet, number and ."

